server:
  host: "0.0.0.0"
  port: 8000
  maxConnections: 10000
  maxBodySize: 1048576

db:
  user: postgres
  password: password
  dbname: postgres
  host: db
  port: 5432

pool:
  bufMaxSize: 1024
  writeTimeout: 1 # seconds
  tableName: "measurements"
